ALTER TABLE users ADD isCreator BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE episodes ADD isListed BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE podcasts ADD isListed BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE podcasts ADD byUserId INTEGER NOT NULL DEFAULT 1;

ALTER TABLE podcasts ADD isDeleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE podcasts ADD isPremium BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE episodes ADD isDeleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE episodes ADD isPremium BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE episodes ADD isFromRss BOOLEAN NOT NULL DEFAULT FALSE;
