ALTER TABLE users ADD isCreator BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE episodes ADD isListed BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE podcasts ADD isListed BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE podcasts ADD byUserId INTEGER NOT NULL DEFAULT 1;

ALTER TABLE podcasts ADD isDeleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE podcasts ADD isPremium BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE episodes ADD isDeleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE episodes ADD isPremium BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE episodes ADD isFromRss BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE wordOccurrences (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  episodeId INTEGER NOT NULL,
  wordId INTEGER NOT NULL,
  time REAL NOT NULL,
  context TEXT NOT NULL,
  FOREIGN KEY (episodeId) REFERENCES episodes(id),
  FOREIGN KEY (wordId) REFERENCES dictionary(id)
);